### PR TITLE
漫画検索を直す

### PR DESCRIPTION
**Pull request by NakashoyaHidetaro**
https://github.com/hidesys/mantropy/issues/29

### CODE REVIEW

**Comment by quiye** [comment]
http://192.168.0.11:3001/search?utf8=%E2%9C%93&str=%E4%B8%AD%E5%B7%9D&commit=%E6%A4%9C%E7%B4%A2&scope=amazon_all
だと
Amazon::AWS::HTTPError in SeriesController#search
HTTP response code 503
ですが
http://192.168.0.11:3001/search?utf8=%E2%9C%93&str=%E5%AE%9D%E7%9F%B3%E3%81%AE%E5%9B%BD&commit=%E6%A4%9C%E7%B4%A2&scope=amazon
だと
2278488051 is out of range for ActiveModel::Type::Integer with limit 4 bytes
ですね

**Comment by NakashoyaHidetaro** [comment]
arigato~~~~~

**Comment by NakashoyaHidetaro** [comment]
対応しました
https://github.com/hidesys/mantropy/issues/8

**Comment by quiye** [comment]
LLLLLGGGGTTTTMMMM

**Pull request merged**
